# Generated by Django 5.0.1 on 2024-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
    ]
