# Generated by Django 5.0.1 on 2024-08-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_uploadedpdf_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='image_urls',
            field=models.JSONField(),
        ),
    ]
